### ISSUE TITLE
Expose Scanner Bytes

### ISSUE THREAD

**Issue by edhaight** [olivere/ndjson#4]
Stumbled across this package and it does most of what I need it to do but I'd like to expose the bufio.Scanner.Bytes() call to debug & persist bad json entries. Failed calls to Decode will return an error, but it would be nice to have access to the underlying buffer that caused the decode error.

**Comment by olivere** [comment]
Maybe we can expose additional information by a custom error type.

**Comment by olivere** [comment]
Have you checked the error returned here?

func (r *Reader) Err() error { … }

If you need more access, maybe copying the source code and using that is the better approach. It’s simple enough.

**Comment by edhaight** [comment]
A custom error type could be nice. Maybe some integration with [gojsonschema](https://github.com/xeipuuv/gojsonschema), but thats probably overkill for most cases.

Ultimately I need full scope of the bad entry, so I think copying is probably the simplest way to go. Thanks for the quick response :-)

**Comment by olivere** [comment]
Had a look at it. I can't see an actual code snippet that wouldn't already give you access to the error details.

* If decoding fails, you get back an e.g. [`*json.SyntaxError`](https://pkg.go.dev/encoding/json@go1.17.1#SyntaxError) in the [`Decode` method](https://github.com/olivere/ndjson/blob/main/reader.go#L60-L64).
* If scanning fails, you get back the underlying error with the [`Err` method](https://github.com/olivere/ndjson/blob/main/reader.go#L55-L58), as [this test](https://github.com/olivere/ndjson/blob/main/reader_test.go#L115-L143) illustrates. 

If you have a different angle and a reproducible test, let me know.

**Comment by edhaight** [comment]
What you said makes sense but to clarify, I was looking to get access to the byte array passed to decode.

**Comment by olivere** [comment]
@edhaight I see. You want very tight control over what the library is doing. I think it might be better to use your own code, especially if it's just a few lines of code.

[Here](https://play.golang.org/p/_Yio0pP6hBQ) is an example of doing just that in a different way.

**Comment by edhaight** [comment]
Thanks for the help, I've copied it over into the project & made the modifications.

But thats actually still more than what I was looking for. Really just looking to get read access to the scanner's token byte buffer after each call to Next. Like [this](https://play.golang.org/p/D_3hXRwjOGt).

The use case is something like dumping all bad json entries to a new file.

**Comment by olivere** [comment]
Fine. I tagged 1.0.1 with a new `Bytes` function on the `Reader`. Thanks for being so patient.
